name: ericpereira
description: Web Site pessoal
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_modular: ^5.0.3
  flutter_triple: ^1.2.7+4
  google_fonts: ^5.1.0
  responsive_builder: ^0.7.1
  url_launcher: ^6.1.10
  provider: ^6.1.2
  font_awesome_flutter: ^10.7.0
  flutter_launch: ^0.3.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.2.1
flutter:
  uses-material-design: true